spring:
  application:
    name: vitals-journal-server

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vitals_journal}
    username: ${DB_USER:vitals}
    password: ${DB_PASSWORD:vitals}
    driver-class-name: org.postgresql.Driver

  mvc:
    problemdetails:
      enabled: true

  web:
    error:
      include-message: never
      include-stacktrace: never
      include-exception: false

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

auth:
  token:
    public-key: ${JWT_PUBLIC_KEY_LOCATION}
    private-key: ${JWT_PRIVATE_KEY_LOCATION}
    access-token-ttl: 15m
    refresh-token-ttl: 14d
